version: '3.7'

services:
  postgres:
    image: 'postgres:15.1-alpine'
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build: ../backend
    restart: always
    volumes:
      - static_volume:/app/backend_static/
      - media_volume:/app/backend_media/
    depends_on:
      - postgres
    env_file:
      - ./.env

  frontend:
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.22.1-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/backend_static/
      - media_volume:/var/html/backend_media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend

volumes:
  db_volume:
  static_volume:
  media_volume:
 